# action.yaml
name: 'npmabot'
description: 'Increment the version of your npm package automatically'
icon: 'arrow-up-circle'
color: 'blue'
inputs:
  version_name:
    description: 'version type to change'
    required: false
    default: "patch"
  package_file_path:
    description: 'package.json full path'
    required: false
    default: 'package.json'
outputs:
  result:
    description: 'Result of the Script'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version_name}}
    - ${{ inputs.package_file_path}}
